<p>Greetings, <?php echo $nick; ?>. You have logged in for <?php echo $count; ?> times.</p>
(<a href="logout.php">logout</a>)	
<h3>Lorem ipsum dolor</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tempus molestie rhoncus.
 Etiam sodales porttitor accumsan. Vivamus a dolor iaculis, porttitor lorem in, dictum libero.
 Fusce eget nibh commodo, sodales justo id, ultricies magna. Mauris sodales, nisl eget tincidunt tempor,
 lacus mauris cursus leo, vitae faucibus turpis sapien quis velit. Donec ultrices est non quam fringilla
 efficitur. Morbi id dictum nulla. Curabitur vitae auctor tellus. Sed maximus est dignissim purus fermentum,
 non dictum velit molestie. Aenean condimentum consequat augue, eget vestibulum leo semper at.
 Duis tellus massa, tempor in purus non, sagittis convallis neque. Aenean nulla nisi, convallis in justo ut,
 efficitur placerat ipsum. Cras efficitur mollis nunc, ut maximus justo imperdiet ac. Nullam vel felis
 vestibulum, laoreet massa vitae, sollicitudin sapien. Morbi pretium, est eget congue cursus, sem ligula
 feugiat est, at interdum odio ligula quis justo. Mauris rhoncus, dui sit amet fermentum maximus, ex elit
 scelerisque elit, et mollis tortor metus id turpis. Nulla ut tellus nec elit imperdiet vehicula.
 Nulla facilisi. Vivamus tempor sed magna at consectetur. Donec imperdiet molestie ex, non pretium nibh
 maximus at. Suspendisse et placerat sem. Nam elementum mauris eget felis auctor, at vehicula diam mollis.
 Curabitur viverra dui vel nibh ornare, ornare lobortis turpis semper. Aliquam sed felis sed ipsum viverra
 ultrices. Fusce vel feugiat ligula. Etiam rutrum finibus nunc, sit amet vehicula enim condimentum in.
 Nunc vitae feugiat nisi. Maecenas et lorem vehicula, dignissim ante et, sodales tortor. Cras tempor, urna
 et sagittis luctus, quam elit laoreet diam, non faucibus metus orci in sem. Vivamus malesuada elementum
 metus eget hendrerit. Morbi non massa iaculis, porta lectus id, pretium risus. Curabitur cursus orci vitae
 elementum fermentum. Pellentesque tempor, metus luctus hendrerit interdum, nibh sem dignissim risus, vel
 rhoncus leo arcu sed nulla. Ut leo ex, aliquam sed dolor a, ornare ullamcorper lorem. Nam sit amet nisl
 sagittis, tincidunt tortor pharetra, iaculis velit. Aliquam id nisl nec lacus maximus maximus ac efficitur 
 justo. Ut ac posuere lectus. Nullam facilisis magna vel tellus congue venenatis. Fusce imperdiet commodo
 nisl sed suscipit. Sed quis nibh suscipit, porttitor lacus sed, pharetra velit. 
</p>